Repository Please-Hug/HugmeEXP_Frontend, pull requests merged in 2025-08, with the labels that each got.

#21 feat: 공고 상세 보기 UI & API 추가
  src/api/recruitmentService.js
  src/assets/logos/jumpit_logo.png
  src/assets/logos/wanted_logo.png
  src/components/recruitment/recruitment_filter/RecruitmentFilter.jsx
  src/components/recruitment/recruitment_filter/SkillSelector.jsx
  src/components/recruitment/recruitment_map/MapContainer.jsx
  src/components/recruitment/recruitment_map/RecruitmentDetail.jsx
  src/components/recruitment/recruitment_map/RecruitmentDetail.module.scss
  src/components/recruitment/recruitment_map/RecruitmentItem.jsx
  src/components/recruitment/recruitment_map/RecruitmentItem.module.scss
  src/constants/recruitmentConstants.js
  src/pages/recruitment/RecruitmentMap.jsx
  src/pages/recruitment/RecruitmentMap.module.scss
Labels: 기능 개발

#25 [Feat] 대시보드에 최신 채용 공고 캐러셀 구현
  package-lock.json
  src/api/recruitmentService.js
  src/components/Dashboard/LatestRecruitmentCarousel.jsx
  src/components/Dashboard/LatestRecruitmentCarousel.module.scss
  src/pages/user/DashboardPage.jsx
Labels: 기능 개발

#31 사이드바에 채용 공고 지도 메뉴 아이템 추가
  src/components/common/Sidebar/Sidebar.jsx
Labels: 기능 개발

#30 [refactor] 프런트 테스트 데이터 삭제 백엔드 데이터로 교체
  src/api/recruitmentService.js
  src/assets/images/marker/select.png
  src/components/recruitment/recruitment_filter/RecruitmentFilter.jsx
  src/components/recruitment/recruitment_filter/RecruitmentFilter.module.scss
  src/components/recruitment/recruitment_filter/SkillSelector.jsx
  src/components/recruitment/recruitment_map/MapContainer.jsx
  src/components/recruitment/recruitment_map/RecruitmentDetail.jsx
  src/components/recruitment/recruitment_map/RecruitmentFilter.jsx
  src/components/recruitment/recruitment_map/RecruitmentFilter.module.scss
  src/pages/recruitment/RecruitmentMap.jsx
Labels: 기능 개발

#36 fix: handleSearchCurrentMap() 로직 수정
  src/pages/recruitment/RecruitmentMap.jsx
Labels: 버그

#39 [fix] QA 1차 적용
  src/components/recruitment/develop/MapBoundaryMarkers.jsx
  src/components/recruitment/develop/MapBoundsDisplay.jsx
  src/components/recruitment/develop/MapBoundsDisplay.module.scss
  src/components/recruitment/recruitment_filter/EducationFilter.jsx
  src/components/recruitment/recruitment_filter/EnhancedSkillSelector.jsx
  src/components/recruitment/recruitment_filter/ExperienceRangeSlider.jsx
  src/components/recruitment/recruitment_filter/RecruitmentFilter.jsx
  src/components/recruitment/recruitment_filter/RecruitmentFilter.module.scss
  src/components/recruitment/recruitment_filter/SalaryFilter.jsx
  src/components/recruitment/recruitment_map/MapContainer.jsx
  src/components/recruitment/recruitment_map/RecruitmentItem.jsx
  src/components/recruitment/recruitment_map/RecruitmentList.jsx
  src/components/recruitment/recruitment_map/RecruitmentSearch.jsx
  src/pages/recruitment/RecruitmentMap.jsx
  src/routes/public.routes.jsx
  src/utils/devModeUtils.js
Labels: 버그, 리팩토링
